version: 2
updates:
  - package-ecosystem: pip
    directory: "/core"
    schedule:
      interval: weekly
    labels: ["dependencies", "python"]

  - package-ecosystem: pip
    directory: "/utils"
    schedule:
      interval: weekly
    labels: ["dependencies", "python"]

  - package-ecosystem: cargo
    directory: "/core-rs"
    schedule:
      interval: weekly
    labels: ["dependencies", "rust"]

  - package-ecosystem: npm
    directory: "/web/frontend"
    schedule:
      interval: weekly
    labels: ["dependencies", "frontend"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels: ["dependencies", "ci"]
