name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: draft release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: release-drafter/release-drafter@v7
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
